### ISSUE TITLE
Start time no longer working on 2024.3

### ISSUE THREAD

**Issue by Dutchy-79** [AlexxIT/StartTime#4]
![Screenshot_20240307_120353_Chrome](https://github.com/AlexxIT/StartTime/assets/22749572/1c9944c4-14bd-4e89-8cc3-03cf4ae2b9f2)

**Comment by dincojazz** [comment]
I'm in the same situation.

**Comment by AlexxIT** [comment]
I guess you don't keep up with the updates.

**Comment by Dutchy-79** [comment]
Checked for update and non available
