### ISSUE TITLE
Fix support Hass 2024.4

### ISSUE THREAD

**Issue by tjorim** [AlexxIT/StartTime#6]
```
This error originated from a custom integration.

Logger: custom_components.start_time.sensor
Source: custom_components/start_time/sensor.py:35
integration: Start Time (documentation, issues)
First occurred: 19:45:23 (1 occurrences)
Last logged: 19:45:23

update error
Traceback (most recent call last):
  File "/config/custom_components/start_time/sensor.py", line 35, in monkey_info
    self.internal_update(args[0])
  File "/config/custom_components/start_time/sensor.py", line 52, in internal_update
    sorted(setup_time.items(), key=lambda kv: kv[1], reverse=True)
TypeError: '<' not supported between instances of 'collections.defaultdict' and 'collections.defaultdict'
```

**Comment by Blacksli** [comment]
Регистратор: custom_components.start_time.sensor
Источник: custom_components/start_time/sensor.py:35
интеграция: Start Time ([документация](https://github.com/AlexxIT/StartTime), [проблемы](https://github.com/AlexxIT/StartTime/issues))
Первое сообщение: 00:24:59 (1 сообщений)
Последнее сообщение: 00:24:59

update error
Traceback (most recent call last):
  File "/config/custom_components/start_time/sensor.py", line 35, in monkey_info
    self.internal_update(args[0])
  File "/config/custom_components/start_time/sensor.py", line 52, in internal_update
    sorted(setup_time.items(), key=lambda kv: kv[1], reverse=True)
TypeError: '<' not supported between instances of 'collections.defaultdict' and 'collections.defaultdict'

**Comment by EvgenyBash** [comment]
Подтверждаю. После обновления на версию 2024.4.0 интеграция перестала работать.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/StartTime/releases/tag/v1.1.8
